Fix MacOS warning (function declaration without prototype)
pcg_basic.c.o -c ../subprojects/deckhandler/subprojects/pcg/pcg_basic.c
../subprojects/deckhandler/subprojects/pcg/pcg_basic.c:69:22: error: a
function declaration without a prototype is deprecated in all versions
of C [-Werror,-Wstrict-prototypes]
uint32_t pcg32_random()